version: '3.7'

services:
  test:
    image: core_app
    container_name: forum_test
    build:
      context: ./application
      dockerfile: docker/Dockerfile
    command:  ["test"]
    depends_on:
      - test_db
    volumes:
      - ./application:/app
    env_file:
      - ./application/.env.testing

  test_db:
    image: postgres:12.1-alpine
    container_name: forum_test_db
    ports:
      - 5433:5433
    env_file:
      - .postgr-env
