version: '3.7'

services:
  nginx:
    image: core_nginx
    build:
      context: .
      dockerfile: nginx/docker/Dockerfile
    command:  ["/bin/sh", "-c", "/usr/share/nginx/dockerize.sh"]
    depends_on:
      - app
    ports:
      - 80:80
    volumes:
      - ./application/public:/usr/share/nginx/html

  app:
    image: core_app
    build:
      context: ./application
      dockerfile: docker/Dockerfile
    command:  ["app"]
    depends_on:
      - db
      - redis
    volumes:
      - ./application:/app
    environment:
      PHP_IDE_CONFIG: "serverName=two"

  worker:
    image: core_app
    build:
      context: ./application
      dockerfile: docker/Dockerfile
    command:  ["worker"]
    depends_on:
      - db
      - redis
    volumes:
      - ./application:/app
    environment:
      PHP_IDE_CONFIG: "serverName=two"

  cron:
    image: core_app
    build:
      context: ./application
      dockerfile: docker/Dockerfile
    command:  ["cron"]
    depends_on:
      - db
      - redis
    volumes:
      - ./application:/app
    environment:
      PHP_IDE_CONFIG: "serverName=two"

  db:
    image: postgres:12.1-alpine
    ports:
      - 5432:5432
    env_file:
      - .postgr-env
    volumes:
      - pgdata:/var/lib/postgresql/pgdata

  redis:
    image: redis:4-alpine
    volumes:
      - redisdata:/data
    ports:
      - 6379:6379


volumes:
  pgdata:
  redisdata: