version: '3.7'

services:
  app:
    image: core_app
    build:
      context: .
      dockerfile: application/docker/Dockerfile
    command:  ["test"]
    depends_on:
      - db
    volumes:
      - .:/app
  db:
    image: postgres:12.1-alpine
    ports:
      - 5432:5432
    env_file:
      - .postgr-env
